apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: genietalk/flask_app:1.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: UNIVERSAL_TFSERVING
              value: "http://universal-tfserving-service:8501/v1/models/universal:predict"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
