apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-nginx-deployment
  labels:
    app: flask-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-nginx
  template:
    metadata:
      labels:
        app: flask-nginx
    spec:
      containers:
        - name: flask-nginx
          image: genietalk/flask_nginx:1.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flask-nginx-service
spec:
  selector:
    app: flask-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
